apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-myreplicaset
  labels:
    app: myapp
    key: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      key: frontend
  template:
    metadata:
      labels:
        key: frontend
    spec:
      containers:
        - name: myapp
          image: nginx
          ports:
            - containerPort: 80
